os:
  - linux
  - osx

branches:
  except:
    - project/appveyor

language: cpp

before_install: . tools/ci/$TRAVIS_OS_NAME/before_install.sh
install: . tools/ci/$TRAVIS_OS_NAME/install.sh
script: . tools/ci/$TRAVIS_OS_NAME/script.sh
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && . tools/ci/$TRAVIS_OS_NAME/after_success.sh || false'

addons:
  apt:
    packages:
    - libqt4-dev
    - libvlc-dev
    - libvlccore-dev
    - p7zip-full
